services:
  - type: web
    name: pratikshalay-backend
    env: node
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: CORS_ORIGIN
        value: "*"
